export const CONFIG = {
  STORAGE_KEY: 'battleBros_progress',
  IMAGE_CACHE_SIZE: 60,
  PRELOAD_AHEAD: 8,
  TWO_PAGE_BREAKPOINT: 900,
  ZOOM_STEP: 1.2,
  ZOOM_MIN: 0.05,
  ZOOM_MAX: 20,
  ANIMATION_DURATION: 200,
  CONTROLS_HIDE_DELAY: 800,
  EDGE_ZONE_THRESHOLD: 0.12,
  SWIPE_THRESHOLD: 50,
  SWIPE_TIMEOUT: 500
};

export const CHAPTER_NUMBER_PATTERN = /chapter\s+(\d+)/i;
